-- MySQL Script generated by MySQL Workbench
-- 12/03/15 10:30:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema JavaBank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema JavaBank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `JavaBank` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `JavaBank` ;

-- -----------------------------------------------------
-- Table `JavaBank`.`accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JavaBank`.`accounts` ;

CREATE TABLE IF NOT EXISTS `JavaBank`.`accounts` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `balance_amount` FLOAT NOT NULL COMMENT '',
  `account_number` VARCHAR(45) NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `address` VARCHAR(45) NULL COMMENT '',
  `city` VARCHAR(45) NULL COMMENT '',
  `limit_amount` FLOAT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `account_number_UNIQUE` (`account_number` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JavaBank`.`transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JavaBank`.`transactions` ;

CREATE TABLE IF NOT EXISTS `JavaBank`.`transactions` (
  `id` BIGINT NOT NULL COMMENT '',
  `sender_account_number` BIGINT NULL COMMENT '',
  `receiver_account_number` VARCHAR(45) NULL COMMENT '',
  `date` DATE NULL COMMENT '',
  `amount` FLOAT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
