//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace c_sharp.StudentService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.hanze.nl/", ConfigurationName="StudentService.Main")]
    public interface Main {
        
        // CODEGEN: Parameter 'Student' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.hanze.nl/Main/getStudentRequest", ReplyAction="http://webservice.hanze.nl/Main/getStudentResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Student")]
        c_sharp.StudentService.getStudentResponse getStudent(c_sharp.StudentService.getStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.hanze.nl/Main/getStudentRequest", ReplyAction="http://webservice.hanze.nl/Main/getStudentResponse")]
        System.Threading.Tasks.Task<c_sharp.StudentService.getStudentResponse> getStudentAsync(c_sharp.StudentService.getStudentRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.hanze.nl/")]
    public partial class student : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string naamField;
        
        private int leeftijdField;
        
        private bool geslachtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string naam {
            get {
                return this.naamField;
            }
            set {
                this.naamField = value;
                this.RaisePropertyChanged("naam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int leeftijd {
            get {
                return this.leeftijdField;
            }
            set {
                this.leeftijdField = value;
                this.RaisePropertyChanged("leeftijd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool geslacht {
            get {
                return this.geslachtField;
            }
            set {
                this.geslachtField = value;
                this.RaisePropertyChanged("geslacht");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStudent", WrapperNamespace="http://webservice.hanze.nl/", IsWrapped=true)]
    public partial class getStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.hanze.nl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string naam;
        
        public getStudentRequest() {
        }
        
        public getStudentRequest(string naam) {
            this.naam = naam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStudentResponse", WrapperNamespace="http://webservice.hanze.nl/", IsWrapped=true)]
    public partial class getStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.hanze.nl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public c_sharp.StudentService.student Student;
        
        public getStudentResponse() {
        }
        
        public getStudentResponse(c_sharp.StudentService.student Student) {
            this.Student = Student;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MainChannel : c_sharp.StudentService.Main, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MainClient : System.ServiceModel.ClientBase<c_sharp.StudentService.Main>, c_sharp.StudentService.Main {
        
        public MainClient() {
        }
        
        public MainClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MainClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        c_sharp.StudentService.getStudentResponse c_sharp.StudentService.Main.getStudent(c_sharp.StudentService.getStudentRequest request) {
            return base.Channel.getStudent(request);
        }
        
        public c_sharp.StudentService.student getStudent(string naam) {
            c_sharp.StudentService.getStudentRequest inValue = new c_sharp.StudentService.getStudentRequest();
            inValue.naam = naam;
            c_sharp.StudentService.getStudentResponse retVal = ((c_sharp.StudentService.Main)(this)).getStudent(inValue);
            return retVal.Student;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<c_sharp.StudentService.getStudentResponse> c_sharp.StudentService.Main.getStudentAsync(c_sharp.StudentService.getStudentRequest request) {
            return base.Channel.getStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<c_sharp.StudentService.getStudentResponse> getStudentAsync(string naam) {
            c_sharp.StudentService.getStudentRequest inValue = new c_sharp.StudentService.getStudentRequest();
            inValue.naam = naam;
            return ((c_sharp.StudentService.Main)(this)).getStudentAsync(inValue);
        }
    }
}
