-- MySQL Script generated by MySQL Workbench
-- 12/03/15 10:30:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema GBA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GBA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GBA` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `GBA` ;

-- -----------------------------------------------------
-- Table `GBA`.`natuurlijkpersonen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GBA`.`natuurlijkpersonen` ;

CREATE TABLE IF NOT EXISTS `GBA`.`natuurlijkpersonen` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `bsn` BIGINT NOT NULL COMMENT '',
  `geslacht` CHAR(1) NULL COMMENT '',
  `initialen` VARCHAR(5) NULL COMMENT '',
  `achternaam` VARCHAR(30) NULL COMMENT '',
  `straatnaam` VARCHAR(30) NULL COMMENT '',
  `nummer` INT NULL COMMENT '',
  `postcode` VARCHAR(6) NULL COMMENT '',
  `woonplaats` VARCHAR(40) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `bsn_UNIQUE` (`bsn` ASC)  COMMENT '')
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS; 

INSERT INTO `GBA`.`natuurlijkpersonen` VALUES (
  1, 128376874681, 'M', 'AG', 'Nanninga', 'teststraat', 12, '9283AC', 'Groningen'
);